version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./vm:/data
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: broccoli
      POSTGRES_PASSWORD: qXmZZ7U8
      POSTGRES_DB: hei
    ports:
      - "5432:5432"
    volumes:
      - ./vm/postgres-data:/var/lib/postgresql/data

